### PR TITLE
Change Fixnum to Integer for Ruby 2.4

### PR DESCRIPTION
**Pull request by hensleyl**
See https://bugs.ruby-lang.org/issues/12005

### CODE REVIEW

**Comment by luciotbc** [comment]
Did does exist any consideration to accept this PR? @bwthomas

**Comment by hensleyl** [comment]
@bwthomas If you add me as a maintainer to this project I would be happy to merge this and release a new gem.

**Comment by bwthomas** [comment]
Sorry folks, I missed the notification. I'll review and look at adding a maintainer.

**Comment by bwthomas** [comment]
Merged, released v0.0.3.

**Pull request merged**
